import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    // position: "fixed",
    marginTop: -300,
  },
  containerSignUp: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    // position: "fixed",
    marginTop: -200,
  },
  containerName: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    // position: "fixed",
    marginTop: -350,
  },
  title: {
    fontStyle: "normal",
    fontSize: 45,
    fontWeight: "400",
    lineHeight: 52,
    // letterSpacing: "0em",
    textAlign: "left",
    paddingLeft: 40,
    paddingBottom: 40,
    alignSelf: "flex-start",
  },
  subheading: {
    fontStyle: "normal",
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 16,
    letterSpacing: 0.5,
    textAlign: "right",
    color: "rgba(0, 0, 0, 0.5)",
    alignSelf: "flex-end",
    margin: 10,
    marginTop: 5,
  },
  subheadingTOS: {
    fontStyle: "normal",
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
    letterSpacing: 0.5,
    textAlign: "center",
    color: "rgba(0, 0, 0, 0.5)",
    alignSelf: "center",
    margin: 10,
  },
  subheadingForgot: {
    fontStyle: "normal",
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
    letterSpacing: 0.5,
    textAlign: "left",
    color: "rgba(0, 0, 0, 0.5)",
    alignSelf: "left",
    margin: 10,
    marginTop: -10,
    paddingBottom: 10,
  },

  subheadingEmail: {
    fontStyle: "normal",
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
    letterSpacing: 0.5,
    textAlign: "center",
    color: "rgba(0, 0, 0, 0.5)",
    alignSelf: "center",
    margin: 20,
    marginTop: 80,
  },
  input: {
    backgroundColor: "#F0F0F0",
    borderRadius: 5,
    height: 50,
    margin: 5,
    width: 342,
    padding: 10,
    alignSelf: "center",
  },
  formButtonContainer: {
    elevation: 8,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderColor: "#79747E",
    borderWidth: 2,
    borderRadius: 7,
    paddingVertical: 12,
    paddingHorizontal: 12,
    height: 44,
    width: 342,
    alignSelf: "center",
    // position: "fixed",
    bottom: "-30%",
  },
  formButtonContainerSignUp: {
    elevation: 8,
    backgroundColor: "#4F4F4F",
    opacity: 0.3,
    borderStyle: "solid",
    borderColor: "#79747E",
    borderWidth: 2,
    borderRadius: 7,
    paddingVertical: 12,
    paddingHorizontal: 12,
    height: 44,
    width: 342,
    alignSelf: "center",
    // position: "fixed",
    bottom: "-30%",
    marginBottom: 100,
  },
  formButtonContainerEmail: {
    elevation: 8,
    backgroundColor: "#4F4F4F",
    borderStyle: "solid",
    borderColor: "#79747E",
    borderWidth: 2,
    borderRadius: 7,
    paddingVertical: 12,
    paddingHorizontal: 12,
    height: 44,
    width: 342,
    alignSelf: "center",
    // position: "fixed",
    bottom: "-30%",
  },
  formButtonText: {
    fontStyle: "normal",
    fontSize: 14,
    fontWeight: "500",
    letterSpacing: 0.1,
    textAlign: "left",
    color: "#333333",
    alignSelf: "center",
  },
  formButtonTextSignUp: {
    fontStyle: "normal",
    fontSize: 14,
    fontWeight: "500",
    letterSpacing: 0.1,
    textAlign: "left",
    color: "#FFFFFF",
    alignSelf: "center",
  },

  tinyLogo: {
    alignSelf: "flex-start",
    padding: 40,
    // position: "fixed",
    top: -20,
  },
});
